---
#
# Debug mode
#
debug_mode: false

#
# All
#
server:
  install: '1'
  packages:
    - vim
    - git
    - imagemagick
    - nodejs
    - npm
  timezone: America/New_York
  locale: en_US.UTF-8
apache:
  install: '1'
  docroot: /vagrant
  servername: myApp.vb
php:
  install: '1'
  # ppa: php
  packages:
    - libapache2-mod-php5
    - php5-cli
    - php5-intl
    - php5-mcrypt
    - php5-mysql
    - php5-curl
    - php5-gd
composer:
  install: '1'
redis:
  install: '1'
  ppa: redis-server
