---
- hosts: all
  tasks:
    - name: install python 2
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
  become: yes
  become_method: sudo
  vars_files:
    - vars/all.yml
    # - vars/ssh_vars.yml
    - vars/platform.yml
    # - vars/deploy.yml

  # Run roles
  roles:
    - server
    - franklinkim.users
    - apache
    - php
    - composer
    # - Datadog.datadog
    # - franklinkim.cron
    # - redis
    # - resque
    # - ssl
    # - carlosbuenosvinos.ansistrano-deploy