---
- name: Update apt
  become: yes
  become_method: sudo
  apt: update_cache=yes

- name: Install System Packages
  become: yes
  become_method: sudo
  apt: pkg={{ item }} state=present
  with_items:
    - curl
    - wget
    - unzip
    - python-software-properties

- name: Install Extra Packages
  become: yes
  become_method: sudo
  apt: pkg={{ item }} state=present
  with_items: server.packages
  when: server.packages is defined

- name: Configure the timezone
  become: yes
  become_method: sudo
  template: src=timezone.tpl dest=/etc/timezone

- name: More Configure the timezone
  become: yes
  become_method: sudo
  file: src=/usr/share/zoneinfo/{{server.timezone}} dest=/etc/localtime state=link force=yes backup=yes

- name: Set default system language pack
  shell: locale-gen {{server.locale}}
  become: yes
  become_method: sudo

- group:
    name: devops
    state: present

- name: Allow 'devops' group to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%devops'
    line: '%devops ALL=(ALL) NOPASSWD:ALL'

- name: Set hostname
  hostname:
    name: "{{ app.servername }}"

# - name: Make `rtcpu` command available for viewing the realtime server CPU utilization percent
#   template:
#     src: rtcpu.tpl
#     dest: /usr/local/bin/rtcpu
#     group: devops
#     owner: site
#     mode: 0777