---
# @see http://docs.ansible.com/ansible/user_module.html
#
# users:
#   - username: foobar              (required)
#     name: Foo Bar
#     uid: 1000
#     group: staff
#     password: xxxxx
#     groups: ["adm", "www-data"]
#     home_mode: "0750"
#     home_create: yes
#     home: /path/to/user/home
#     system: no
#     authorized_keys: []           (required)
#     ssh_key_type: rsa
#     ssh_key_bits: 2048
#     ssh_key_password: ""
#     ssh_key_generate: no
#     ssh_key: "xxx"
#     shell: /bin/bash
#

# array of users to add
users: []
# users home directory
users_home: /home
# default user primary group for users
users_group:
# default user secondary groups
users_groups: []
# default user home directory permissions
users_home_mode: "0755"
