---

#
# Create the basic directory structure of the files to be shared
#
- name: Configure shared directory structure
  become: true
  become_method: sudo
  file:
    path: "{{ site.shared }}/{{ item }}"
    state: directory
    mode: 0755
    group: site
    owner: site
  with_items: dirs.shared

- name: Create .htaccess
  template:
    src: "{{ playbook_dir }}/deploy-tasks/templates/htaccess.tpl"
    dest: "{{ site.shared }}/.htaccess"
    group: site
    owner: site

- name: Create site.php
  template:
    src: "{{ playbook_dir }}/deploy-tasks/templates/site.tpl"
    dest: "{{ site.shared }}/app/Config/site.php"
    group: site
    owner: site

- name: Create robots.txt
  template:
    src: "{{ playbook_dir }}/deploy-tasks/templates/robots.tpl"
    dest: "{{ site.shared }}/app/webroot/robots.txt"
    group: site
    owner: site

- name: Create temporary files directories
  become: true
  become_method: sudo
  file:
    path: "{{ site.shared }}/{{ item }}"
    state: directory
    mode: 0777
    owner: site
    group: site
  with_items: dirs.tmp

#
# Upload the Wordpress files, if necessary
#
- name: Check for existence of Wordpress files
  stat:
    path: "{{ site.shared }}/app/webroot/wordpress"
  register: wp

- name: Copy Wordpress files to server
  unarchive:
    src: "{{ playbook_dir }}/deploy-tasks/templates/wordpress.zip"
    dest: "{{ site.shared }}/app/webroot"
  when: wp.stat.exists == False