---
#
# Instal Redis
#
- name: Install Redis
  become: yes
  become_method: sudo
  apt: pkg=redis-server state=latest

#
# Disable the default init.d script for redis:
#
- name: Disable default init.d for redis
  become: yes
  become_method: sudo
  command: update-rc.d redis-server disable

#
# Create the upstart script
#
- name: Create the upstart script
  template:
    src: redis-server.conf.tpl
    dest: /etc/init/redis-server.conf

#
# De-daemonize redis-server
#
- name: De-daemonize redis-server
  replace:
    dest: /etc/redis/redis.conf
    regexp: '(daemonize yes)'
    replace: 'daemonize no'
  notify: start redis-server