---
# - name: Add Ondrej/PHP ppa Repository
#   become: yes
#   become_method: sudo
#   apt_repository:
#     repo: ppa:ondrej/{{ php.ppa }}
#     state: present

- name: Update apt
  become: yes
  become_method: sudo
  apt: update_cache=yes

- name: Install PHP 5.5
  become: yes
  become_method: sudo
  apt: pkg=php5 state=latest

- name: Install php5-fpm
  become: yes
  become_method: sudo
  apt: pkg=php5-fpm state=latest

- name: Install PHP Packages
  become: yes
  become_method: sudo
  apt: pkg={{ item }} state=latest
  with_items: php.packages
  when: php.packages is defined

- name: Enable mcrypt php module
  become: yes
  become_method: sudo
  shell: php5enmod mcrypt

- include: configure.yml
- include: pecl.yml
