---
- name: ensure timezone is set in apache2 php.ini
  lineinfile: dest=/etc/php5/apache2/php.ini
              regexp='date.timezone ='
              line='date.timezone = {{ server.timezone }}'

- name: set max memory in php.ini
  lineinfile: dest=/etc/php5/apache2/php.ini
              regexp='memory_limit ='
              line='memory_limit = 2G'

- name: set max memory in php.ini
  lineinfile: dest=/etc/php5/apache2/php.ini
              regexp='memory_limit ='
              line='memory_limit = 2G'

- name: set short tag on in php.ini
  lineinfile: dest=/etc/php5/apache2/php.ini
              regexp='short_open_tag ='
              line='short_open_tag = On'

- name: enabling opcache
  lineinfile: dest=/etc/php5/apache2/php.ini
              regexp=';?opcache.enable=\d'
              line='opcache.enable=1'

- name: enable pcntl
  replace:
    dest: /etc/php5/apache2/php.ini
    regexp: 'disable_functions'
    replace: ';disable_functions'

- name: set session path to /var/lib/php5/session
  replace:
    dest: /etc/php5/apache2/php.ini
    regexp: ';?session.save_path.*$'
    replace: 'session.save_path = "/var/lib/php5/session"'

- name: set session.gc_probability for cleanup of old session files
  replace:
    dest: /etc/php5/apache2/php.ini
    regexp: 'session.gc_probability ='
    replace: 'session.gc_probability = 1'

- name: Ensure /var/lib/php5/session exists and is writable by the site user
  become: true
  become_method: sudo
  file:
    path: "/var/lib/php5/session"
    state: directory
    mode: 0755
    owner: "{{ session.user }}"
    group: "{{ session.user }}"
