---

- find: paths="{{ env_local_dir }}" patterns="*" file_type=directory
  register: local_sites

- debug: msg="Couldn't copy env local configs!"
  when: local_sites.files|length < 1

- name: Copy env general config
  shell: "cp config.php.default config.php"
  args:
    chdir: "{{ env_local_dir }}"

- name: Copy site env_configs
  shell: "cp {{ item.path }}/env_config.php.default {{ item.path }}/env_config.php"
  with_items: "{{ local_sites.files }}"
  args:
    chdir: "{{ env_local_dir }}"

- name: Copy default htaccess
  shell: "cp htaccess.default .htaccess"
  args:
    chdir: "{{ apache.docroot }}"

- name: Remove unix_socket from db config
  lineinfile: dest="{{ env_local_dir }}/config.php" state=absent regexp="unix_socket"

- name: Run bin/setup
  shell: bin/setup
  args:
    chdir: "{{ apache.docroot }}"