---
- name: Set the hostname in /etc/hostname
  shell: echo {{ vagrant_local.vm.hostname }} > /etc/hostname
  when: vagrant_local.vm.hostname is defined

- name: Set the hostname
  shell: hostname {{ vagrant_local.vm.hostname }}
  when: vagrant_local.vm.hostname is defined

- name: Update /etc/hosts
  lineinfile: dest=/etc/hosts line="127.0.0.1 localhost {{ item }}" owner=root group=root mode=0644
  with_items: "{{ app.names }}"
